# this file is autogenerated by .github/workflows/update.yml
{
  description = "nix-index database";
  outputs = _:
    {
      legacyPackages.x86_64-linux.database = builtins.fetchurl {
        url = "https://github.com/Mic92/nix-index-database/releases/download/2022-09-11/index-x86_64-linux";
        sha256 = "1s10gnak29ksrxfa11lpi7w4bg7fkb3l7jmwhd3y5jnw53vc6yb1";
      };
      legacyPackages.x86_64-darwin.database = builtins.fetchurl {
        url = "https://github.com/Mic92/nix-index-database/releases/download/2022-09-11/index-x86_64-darwin";
        sha256 = "1x7sxjw4azjxhimab4pkvsjzwq4jj2y78hh1bsx1yjq7idvrp72q";
      };
    };
}
