# this file is autogenerated by .github/workflows/update.yml
{
  description = "nix-index database";
  outputs = _:
    {
      legacyPackages.x86_64-linux.database = builtins.fetchurl {
        url = "https://github.com/Mic92/nix-index-database/releases/download/2022-12-25/index-x86_64-linux";
        sha256 = "";
      };
      legacyPackages.x86_64-darwin.database = builtins.fetchurl {
        url = "https://github.com/Mic92/nix-index-database/releases/download/2022-12-25/index-x86_64-darwin";
        sha256 = "";
      };
      legacyPackages.aarch64-linux.database = builtins.fetchurl {
        url = "https://github.com/Mic92/nix-index-database/releases/download/2022-12-25/index-aarch64-linux";
        sha256 = "";
      };
    };
}
