# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/nix-community/nix-index-database/releases/download/2024-08-04-025735/index-";
  hashes = {
    x86_64-linux = "sha256-T9ouwO2vRtZdabzmDZRBMZqqfCir2lexiITcKVHMgXY=";
    aarch64-linux = "sha256-EToCZsNd6MYod0j2YZUCzsKI9nTjKjZga96xERKevcc=";
    x86_64-darwin = "sha256-PPQnkdbxVG3PoR9Max961F8GYURshhbEQigJVQf7zLQ=";
    aarch64-darwin = "sha256-MlSbtl/Syx+8+CGUzZzov8xl/b95odkYLAVrZUFnlUs=";
  };
}
