# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/nix-community/nix-index-database/releases/download/2024-12-26-140211/index-";
  hashes = {
    x86_64-linux = "sha256-Sfp2JO/mKort3JZG2NJR3TIK52m5juYs34v4B1Jwzjk=";
    aarch64-linux = "sha256-KlmcR7KEOf+7U35iCfPN4zRlM0tBifAETRa59uhQBxk=";
    x86_64-darwin = "sha256-BfmuJ9zZhjjW3v7ezD6cYPEdUjnTjDPDqLg0UQ0h5xs=";
    aarch64-darwin = "sha256-JGyEeGfFJBCr4VikWmwjtGMYnsw3nWVbRPdYhfjTb24=";
    x86_64-linux-small = "sha256-BH0aSTQMyFDJjajv4z7Jq+8ve4/dho0PBZqpLgrjjaM=";
    aarch64-linux-small = "sha256-J9udVukNIKVaFqmXNwGYxAox+r0gASWBgToNt5p5eUs=";
    x86_64-darwin-small = "sha256-hwJb5u0ueXJ3GmztJiaxaneGQJxNkYqum589UFyOj4I=";
    aarch64-darwin-small = "sha256-OjwdWx4NrgX6PuRqL7KLo7XbRKjkfYYTWFmzS0qxqq4=";
  };
}
