# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/nix-community/nix-index-database/releases/download/2024-12-29-031725/index-";
  hashes = {
    x86_64-linux = "sha256-a0yieztD5BaCNv1iMj9DBlXxpU+t8LI8cbD5gTL28Ww=";
    aarch64-linux = "sha256-KxRhl7M0dalLFKlCA4zZsN2+1WlQ6MzSk1Wg3reAiGk=";
    x86_64-darwin = "sha256-uQ4fV780tu1PtSYpzpq47d0VKSqmIa0QWLOukXLM8XM=";
    aarch64-darwin = "sha256-EBbdno5JZ2PIzcwyYQ4prciu62Xh7spIg/+r5AVoWq4=";
    x86_64-linux-small = "sha256-vRSQIymf7gXBLciJxvPb6rJ3zI4xYxyJJASjIPXc+UM=";
    aarch64-linux-small = "sha256-k/+8q9SDWVNJJHw82U2j+qCm8Qd/+J63K/KKNEzuEps=";
    x86_64-darwin-small = "sha256-5hODqUzOcvLdcol3zZJrmUY177FX4XrMBL0LJTAzHAQ=";
    aarch64-darwin-small = "sha256-z3agSuqvh7RVG9Cu4EuhEeyvVatLCyWAOTmZswfDyG4=";
  };
}
