# this file is autogenerated by .github/workflows/update.yml
{
  x86_64-linux.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-01-28-030920/index-x86_64-linux";
    sha256 = "1xdsr9s1bxxjswf72s215zc3pp44863j1ldm487f3d1wk1qqhfqr";
  };
  aarch64-linux.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-01-28-030920/index-aarch64-linux";
    sha256 = "1m9iahblfnh44lf1k3k6kcw4l2yn32b0fpm5fc09vc00rwwwkp32";
  };
  x86_64-darwin.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-01-28-030920/index-x86_64-darwin";
    sha256 = "042kr18jx9sakdbxfaigdb3cpd7277vymmbajqlync3kwjarma35";
   };
  aarch64-darwin.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-01-28-030920/index-aarch64-darwin";
    sha256 = "05w8cifp919rlqwdfn0l4mcbrhg6sgsin16480pqxqgywxyp8y1q";
  };
}
