# this file is autogenerated by .github/workflows/update.yml
{
  x86_64-linux.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-05-19-030652/index-x86_64-linux";
    sha256 = "064c8qnfgw44m8n1jw4v5wmr5ji6plzj04m1max97b5979laxg2v";
  };
  aarch64-linux.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-05-19-030652/index-aarch64-linux";
    sha256 = "1wki24lbngp3y33pr96jybny1gsjff7gnjnwi1bzp2z2p7khf8l3";
  };
  x86_64-darwin.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-05-19-030652/index-x86_64-darwin";
    sha256 = "1c2mrvxwrdx4yab7wsad0pq2rrjkcnp2xjiqh115r2aj5ma1q2mc";
   };
  aarch64-darwin.database = builtins.fetchurl {
    url = "https://github.com/nix-community/nix-index-database/releases/download/2024-05-19-030652/index-aarch64-darwin";
    sha256 = "1vk56gis5akmk6k8454h99fvggm9naj10r5v313vjpw0z4rsvi09";
  };
}
